server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/viralpe
    username: postgres
    password: postgress
  jpa:
    hibernate:
      ddl-auto: none
# developed by anika teja reddy
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: INFO