import { TransactionReceiptDetails } from '../components/TransactionReceiptModal';

export function createReceiptPDFBlob(
  details: TransactionReceiptDetails,
  userName: string,
  userPincode: string
): Promise<Blob> {
  return new Promise((resolve) => {
    const canvas = document.createElement('canvas');
    const width = 600;
    const height = 900;
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d')!;

    // 1. Clean White Background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, width, height);

    // 2. Top Header Gradient Bar (#00685b -> #004d43)
    const grad = ctx.createLinearGradient(0, 0, width, 0);
    grad.addColorStop(0, '#00685b');
    grad.addColorStop(1, '#004d43');
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, width, 110);

    // Header Text
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 22px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('VIRALPE WALLET NETWORK', width / 2, 48);

    ctx.font = '600 13px sans-serif';
    ctx.fillStyle = 'rgba(255, 255, 255, 0.85)';
    ctx.fillText('OFFICIAL TRANSACTION RECEIPT', width / 2, 75);

    // 3. Success Badge Icon (Circular Emerald Badge + Checkmark)
    ctx.beginPath();
    ctx.arc(width / 2, 160, 36, 0, Math.PI * 2);
    ctx.fillStyle = '#00685b';
    ctx.fill();

    // Checkmark
    ctx.strokeStyle = '#ffffff';
    ctx.lineWidth = 5;
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctx.beginPath();
    ctx.moveTo(width / 2 - 14, 160);
    ctx.lineTo(width / 2 - 4, 170);
    ctx.lineTo(width / 2 + 14, 150);
    ctx.stroke();

    // Status Header & Big Amount
    ctx.fillStyle = '#0f172a';
    ctx.font = 'bold 20px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('Transaction Successful!', width / 2, 230);

    ctx.fillStyle = '#00685b';
    ctx.font = '900 42px sans-serif';
    ctx.fillText(`RS ${details.amount.toFixed(2)}`, width / 2, 280);

    ctx.fillStyle = '#64748b';
    ctx.font = '600 14px sans-serif';
    ctx.fillText(`On ${details.operator || 'Mobile'} Recharge - ${details.mobileNumber || ''}`, width / 2, 310);

    // 4. Congratulations & Royalty Card
    const cardY = 340;
    ctx.fillStyle = '#e6f4f1';
    ctx.beginPath();
    ctx.roundRect(40, cardY, width - 80, 115, 16);
    ctx.fill();
    ctx.strokeStyle = '#84cc16';
    ctx.lineWidth = 1;
    ctx.stroke();

    ctx.fillStyle = '#0f172a';
    ctx.font = 'bold 16px sans-serif';
    ctx.fillText(`Congratulations ${userName}!`, width / 2, cardY + 30);

    const cashback = (details.cashbackEarned ?? Math.round(details.amount * 0.02 * 100) / 100).toFixed(2);
    const pincodeRoyalty = (details.pincodeRoyaltyEarned ?? Math.round(details.amount * 0.005 * 100) / 100).toFixed(2);
    const totalGen = (parseFloat(cashback) + parseFloat(pincodeRoyalty)).toFixed(2);

    ctx.fillStyle = '#00685b';
    ctx.font = '700 14px sans-serif';
    ctx.fillText(`You earned RS ${cashback} Cashback`, width / 2, cardY + 54);

    ctx.fillStyle = '#475569';
    ctx.font = '500 13px sans-serif';
    ctx.fillText(`Your Pincode (${userPincode}) earned RS ${pincodeRoyalty} Zonal Royalty`, width / 2, cardY + 76);

    ctx.fillStyle = '#0f172a';
    ctx.font = '700 13px sans-serif';
    ctx.fillText(`Total Generated by this payment: RS ${totalGen}`, width / 2, cardY + 98);

    // 5. Details Table Box
    const tableY = 480;
    ctx.fillStyle = '#f8fafc';
    ctx.beginPath();
    ctx.roundRect(40, tableY, width - 80, 310, 16);
    ctx.fill();
    ctx.strokeStyle = '#cbd5e1';
    ctx.lineWidth = 1.5;
    ctx.stroke();

    const formattedDate = details.paidOn || new Date().toLocaleString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    });

    const rows = [
      { label: 'STATUS', val: details.status || 'SUCCESS', isBadge: true },
      { label: 'PAID ON', val: formattedDate },
      { label: 'FUNDING MODE', val: details.fundingMode || 'GATEWAY' },
      { label: 'PAID BY GATEWAY', val: `RS ${(details.paidByGateway ?? details.amount).toFixed(2)}` },
      { label: 'PAID BY WALLET', val: `RS ${(details.paidByWallet ?? 0).toFixed(2)}` },
      { label: 'DESCRIPTION', val: (details.description || `Mobile recharge ${details.mobileNumber}`).substring(0, 34) },
      { label: 'REFERENCE ID', val: details.referenceId }
    ];

    let rowY = tableY + 36;
    rows.forEach((r, idx) => {
      ctx.textAlign = 'left';
      ctx.fillStyle = '#64748b';
      ctx.font = '600 13px sans-serif';
      ctx.fillText(r.label, 65, rowY);

      ctx.textAlign = 'right';
      if (r.isBadge) {
        // Status Badge Pill
        ctx.fillStyle = '#d1fae5';
        ctx.beginPath();
        ctx.roundRect(width - 150, rowY - 16, 85, 24, 12);
        ctx.fill();
        ctx.fillStyle = '#059669';
        ctx.font = 'bold 12px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(r.val, width - 107.5, rowY);
      } else {
        ctx.fillStyle = '#0f172a';
        ctx.font = 'bold 13px sans-serif';
        ctx.fillText(r.val, width - 65, rowY);
      }

      if (idx < rows.length - 1) {
        ctx.strokeStyle = '#f1f5f9';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(65, rowY + 12);
        ctx.lineTo(width - 65, rowY + 12);
        ctx.stroke();
      }
      rowY += 40;
    });

    // 6. Footer
    ctx.textAlign = 'center';
    ctx.fillStyle = '#94a3b8';
    ctx.font = '500 12px sans-serif';
    ctx.fillText('Secured & Verified by ViralPe Wallet Network', width / 2, height - 35);

    // Convert Canvas to High Quality JPEG & Embed in Native PDF
    const dataUrl = canvas.toDataURL('image/jpeg', 0.95);
    const base64Data = dataUrl.split(',')[1];
    
    const pdfBlob = createPdfWithImageData(base64Data, width, height);
    resolve(pdfBlob);
  });
}

function createPdfWithImageData(base64Image: string, width: number, height: number): Blob {
  const binaryImg = atob(base64Image);
  const imgLen = binaryImg.length;
  
  const imgArray = new Uint8Array(imgLen);
  for (let i = 0; i < imgLen; i++) {
    imgArray[i] = binaryImg.charCodeAt(i);
  }

  const pdfHeader = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /XObject << /Im1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 55 >>
stream
q
595 0 0 842 0 0 cm
/Im1 Do
Q
endstream
endobj
5 0 obj
<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${imgLen} >>
stream
`;

  const pdfFooter = `
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000250 00000 n 
0000000355 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${500 + imgLen}
%%EOF`;

  const headerArray = new TextEncoder().encode(pdfHeader);
  const footerArray = new TextEncoder().encode(pdfFooter);

  const totalLength = headerArray.length + imgArray.length + footerArray.length;
  const fullPdf = new Uint8Array(totalLength);
  fullPdf.set(headerArray, 0);
  fullPdf.set(imgArray, headerArray.length);
  fullPdf.set(footerArray, headerArray.length + imgArray.length);

  return new Blob([fullPdf], { type: 'application/pdf' });
}
